version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: exam_postgres
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-exam_db}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: exam_localstack
    restart: unless-stopped
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=0

volumes:
  postgres_data:
    driver: local
